CREATE DATABASE IF NOT EXISTS CHRONOS;

CREATE SCHEMA IF NOT EXISTS CHRONOS.GOLD;

CREATE SCHEMA IF NOT EXISTS CHRONOS.AI;

SHOW SCHEMAS IN DATABASE CHRONOS;

CREATE OR REPLACE TABLE CHRONOS.GOLD.RECONCILED_EVENTS (
    BUSINESS_EVENT_KEY VARCHAR,
    TICKER VARCHAR,
    EVENT_TIME TIMESTAMP,
    CANONICAL_REVENUE NUMBER(18,2),
    CURRENCY VARCHAR,
    STATUS VARCHAR,
    CANONICAL_SOURCE VARCHAR,
    SOURCE_PRIORITY INTEGER,
    VENDOR_COUNT INTEGER,
    REVENUE_VALUE_COUNT INTEGER,
    HAS_CONFLICT BOOLEAN,
    RECONCILIATION_STATUS VARCHAR,
    CONFIDENCE VARCHAR,
    RECORD_VERSION INTEGER,
    KNOWLEDGE_TIME TIMESTAMP,
    SOURCE_FILE VARCHAR,
    BATCH_ID VARCHAR
);


CREATE OR REPLACE TABLE CHRONOS.GOLD.RECONCILIATION_EVIDENCE (
    BUSINESS_EVENT_KEY VARCHAR,
    TICKER VARCHAR,
    EVENT_TIME TIMESTAMP,

    VENDOR VARCHAR,
    REVENUE NUMBER(18,2),
    CURRENCY VARCHAR,

    SOURCE_PRIORITY INTEGER,
    SOURCE_RANK INTEGER,

    VENDOR_COUNT INTEGER,
    REVENUE_VALUE_COUNT INTEGER,
    HAS_CONFLICT BOOLEAN,

    RECONCILIATION_ROLE VARCHAR,
    RECONCILIATION_REASON VARCHAR,

    KNOWLEDGE_TIME TIMESTAMP,
    RECORD_VERSION INTEGER,

    SOURCE_FILE VARCHAR,
    BATCH_ID VARCHAR
);

select * from chronos.gold.reconciled_events;
truncate table chronos.gold.reconciled_events;

SELECT *
FROM CHRONOS.GOLD.RECONCILIATION_EVIDENCE
ORDER BY TICKER, EVENT_TIME, SOURCE_RANK;

SELECT *
FROM CHRONOS.GOLD.RECONCILED_EVENTS
ORDER BY TICKER, EVENT_TIME;

SELECT
    TICKER,
    EVENT_TIME,
    CANONICAL_REVENUE,
    CANONICAL_SOURCE,
    RECONCILIATION_STATUS,
    CONFIDENCE
FROM CHRONOS.GOLD.RECONCILED_EVENTS
ORDER BY TICKER, EVENT_TIME;


CREATE OR REPLACE VIEW CHRONOS.GOLD.V_AI_FINANCIAL_EVENTS AS

SELECT
    TICKER,
    EVENT_TIME,
    CANONICAL_REVENUE AS REVENUE,
    CURRENCY,
    STATUS,
    CANONICAL_SOURCE AS SOURCE,
    RECONCILIATION_STATUS,
    CONFIDENCE,
    VENDOR_COUNT,
    HAS_CONFLICT,
    KNOWLEDGE_TIME
FROM CHRONOS.GOLD.RECONCILED_EVENTS;

SELECT
    TICKER,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM CHRONOS.GOLD.V_AI_FINANCIAL_EVENTS
GROUP BY TICKER
ORDER BY TOTAL_REVENUE DESC;

CREATE OR REPLACE TABLE CHRONOS.AI.DATA_DICTIONARY (
    TABLE_NAME VARCHAR,
    COLUMN_NAME VARCHAR,
    DESCRIPTION VARCHAR,
    DATA_TYPE VARCHAR,
    BUSINESS_MEANING VARCHAR
);

INSERT INTO CHRONOS.AI.DATA_DICTIONARY VALUES

(
    'V_AI_FINANCIAL_EVENTS',
    'TICKER',
    'Security ticker symbol',
    'VARCHAR',
    'Identifier of the financial security'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'EVENT_TIME',
    'Business event date',
    'TIMESTAMP',
    'Date when the business event occurred'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'REVENUE',
    'Canonical reconciled revenue',
    'NUMBER',
    'Revenue value selected by Chronos reconciliation policy'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'SOURCE',
    'Source selected by reconciliation',
    'VARCHAR',
    'Vendor whose observation became canonical'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'RECONCILIATION_STATUS',
    'Result of reconciliation',
    'VARCHAR',
    'Indicates whether the value was single-source, agreed, or conflict-resolved'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'CONFIDENCE',
    'Business confidence classification',
    'VARCHAR',
    'Confidence assigned by the reconciliation policy'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'VENDOR_COUNT',
    'Number of vendors contributing observations',
    'INTEGER',
    'Number of distinct vendors reporting the business event'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'HAS_CONFLICT',
    'Whether vendors reported different values',
    'BOOLEAN',
    'Indicates whether cross-vendor values disagreed'
),

(
    'V_AI_FINANCIAL_EVENTS',
    'KNOWLEDGE_TIME',
    'Time Chronos learned the canonical observation',
    'TIMESTAMP',
    'System knowledge timestamp'
);

CREATE OR REPLACE TABLE CHRONOS.AI.QUERY_LOG (
    QUERY_ID VARCHAR,
    USER_QUESTION VARCHAR,
    GENERATED_SQL VARCHAR,
    VALIDATION_STATUS VARCHAR,
    VALIDATION_REASON VARCHAR,
    ROW_COUNT INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);