from langgraph.graph import StateGraph, START, END

from src.agents.state import SQLAgentState
from src.agents.snowflake_client import SnowflakeClient
from src.agents.schema_context import SchemaContext
from src.agents.sql_generator import SQLGenerator
from src.agents.answer_generator import AnswerGenerator
from src.agents.sql_validator import validate_sql


# ---------------------------------------------------------
# Initialize shared components
# ---------------------------------------------------------

snowflake = SnowflakeClient()
schema_context_loader = SchemaContext(snowflake)
sql_generator = SQLGenerator()
answer_generator = AnswerGenerator()


# ---------------------------------------------------------
# Node 1: Retrieve schema
# ---------------------------------------------------------

def retrieve_schema(state: SQLAgentState):

    print("\n--- RETRIEVE SCHEMA ---")

    schema = schema_context_loader.get_context()

    return {
        "schema_context": schema
    }


# ---------------------------------------------------------
# Node 2: Generate SQL
# ---------------------------------------------------------

def generate_sql(state: SQLAgentState):

    print("\n--- GENERATE SQL ---")

    question = state["question"]
    schema_context = state["schema_context"]

    sql = sql_generator.generate(
        question=question,
        schema_context=schema_context
    )

    print("\nGenerated SQL:")
    print(sql)

    return {
        "generated_sql": sql
    }


# ---------------------------------------------------------
# Node 3: Validate SQL
# ---------------------------------------------------------

def validate_generated_sql(state: SQLAgentState):

    print("\n--- VALIDATE SQL ---")

    sql = state["generated_sql"]

    validation = validate_sql(sql)

    print(f"Validation: {validation}")

    if validation["valid"]:
        return {
            "validation_status": "PASS",
            "validation_reason": validation["reason"]
        }

    return {
        "validation_status": "FAIL",
        "validation_reason": validation["reason"]
    }

#-----supervisor node-----#
def supervisor_node(state: ChronosState):

    print("\n--- SUPERVISOR ---")

    result = supervisor.route(
        state["question"]
    )

    print(f"Route: {result['route']}")
    print(f"Reason: {result['routing_reason']}")

    return {
        "route": result["route"],
        "routing_reason": result["routing_reason"]
    }
    


# ---------------------------------------------------------
# Node 4: Repair SQL
# ---------------------------------------------------------

def repair_sql(state: SQLAgentState):

    print("\n--- REPAIR SQL ---")

    attempts = state.get("repair_attempts", 0)

    print(f"Repair attempt: {attempts + 1}")

    previous_sql = state["generated_sql"]
    validation_reason = state["validation_reason"]
    schema_context = state["schema_context"]
    question = state["question"]

    repair_prompt = f"""
You are repairing SQL generated by another AI agent.

USER QUESTION:
{question}

SCHEMA:
{schema_context}

PREVIOUS SQL:
{previous_sql}

VALIDATION FAILURE:
{validation_reason}

Generate a corrected SQL query.

Rules:

1. Return ONLY SQL.
2. Use only CHRONOS.GOLD.V_AI_FINANCIAL_EVENTS.
3. Generate SELECT or WITH only.
4. Do not modify data.
5. Do not use INSERT.
6. Do not use UPDATE.
7. Do not use DELETE.
8. Do not use DROP.
9. Do not use ALTER.
10. Do not use CREATE.
11. Do not use MERGE.
12. Do not invent columns.

Correct the SQL based on the validation failure.
"""

    messages = sql_generator.prompt.format_messages(
        question=repair_prompt,
        schema_context=schema_context
    )

    response = sql_generator.llm.invoke(messages)

    repaired_sql = response.content.strip()

    print("\nRepaired SQL:")
    print(repaired_sql)

    return {
        "generated_sql": repaired_sql,
        "repair_attempts": attempts + 1
    }


# ---------------------------------------------------------
# Node 5: Execute SQL
# ---------------------------------------------------------

def execute_sql(state: SQLAgentState):

    print("\n--- EXECUTE SQL ---")

    sql = state["generated_sql"]

    try:

        result = snowflake.execute_query(sql)

        print(
            f"Query returned {result['row_count']} rows"
        )

        return {
            "query_result": result
        }

    except Exception as e:

        print(f"Snowflake execution failed: {e}")

        return {
            "error": str(e)
        }


# ---------------------------------------------------------
# Node 6: Validate result
# ---------------------------------------------------------

def validate_result(state: SQLAgentState):

    print("\n--- VALIDATE RESULT ---")

    result = state.get("query_result")

    if result is None:

        return {
            "error": "No query result returned"
        }

    row_count = result["row_count"]

    print(f"Result contains {row_count} rows")

    return {
        "validation_status": "RESULT_VALID"
    }


def final_answer_node(state):

    if state["route"] == "SQL":

        answer = answer_generator.generate(
            question=state["question"],
            sql=state["generated_sql"],
            result=state["query_result"]
        )

    else:

        answer = generate_rag_answer(
            state["question"],
            state["retrieval_context"]
        )

    return {
        "answer": answer
    }

# ---------------------------------------------------------
# Node 7: Generate final answer
# ---------------------------------------------------------

def generate_final_answer(state: SQLAgentState):

    print("\n--- GENERATE FINAL ANSWER ---")

    answer = answer_generator.generate(
        question=state["question"],
        sql=state["generated_sql"],
        result=state["query_result"]
    )

    print("\nFinal answer:")
    print(answer)

    return {
        "answer": answer
    }


# ---------------------------------------------------------
# Conditional routing
# ---------------------------------------------------------

def route_after_validation(state: SQLAgentState):

    if state["validation_status"] == "PASS":

        return "execute_sql"

    attempts = state.get("repair_attempts", 0)

    if attempts >= 2:

        return "end_with_error"

    return "repair_sql"

#---route from supervisor---#
def route_from_supervisor(state: ChronosState):

    route = state["route"]

    if route == "SQL":
        return "sql_agent"

    if route == "RAG":
        return "rag_agent"

    return "error"

# ---------------------------------------------------------
# Error termination
# ---------------------------------------------------------

def end_with_error(state: SQLAgentState):

    print("\n--- SQL VALIDATION FAILED ---")

    return {
        "error": (
            "SQL could not be validated after "
            f"{state.get('repair_attempts', 0)} repair attempts."
        )
    }


# ---------------------------------------------------------
# Build graph
# ---------------------------------------------------------

def build_graph():

    graph = StateGraph(SQLAgentState)

    # Add nodes
    graph.add_node(
        "retrieve_schema",
        retrieve_schema
    )

    graph.add_node(
        "generate_sql",
        generate_sql
    )

    graph.add_node(
        "validate_sql",
        validate_generated_sql
    )

    graph.add_node(
        "repair_sql",
        repair_sql
    )

    graph.add_node(
        "execute_sql",
        execute_sql
    )

    graph.add_node(
        "validate_result",
        validate_result
    )

    graph.add_node(
        "generate_answer",
        generate_final_answer
    )

    graph.add_node(
        "end_with_error",
        end_with_error
    )

    # -----------------------------------------------------
    # Edges
    # -----------------------------------------------------

    graph.add_edge(
        START,
        "retrieve_schema"
    )

    graph.add_edge(
        "retrieve_schema",
        "generate_sql"
    )

    graph.add_edge(
        "generate_sql",
        "validate_sql"
    )

    graph.add_conditional_edges(
        "validate_sql",
        route_after_validation,
        {
            "execute_sql": "execute_sql",
            "repair_sql": "repair_sql",
            "end_with_error": "end_with_error"
        }
    )
    
    graph.add_conditional_edges(
    "supervisor",
    route_from_supervisor,
    {
        "sql_agent": "sql_agent",
        "rag_agent": "rag_agent",
        "error": "error"
    })

    # Repair goes back through validation
    graph.add_edge(
        "repair_sql",
        "validate_sql"
    )

    graph.add_edge(
        "execute_sql",
        "validate_result"
    )

    graph.add_edge(
        "validate_result",
        "generate_answer"
    )

    graph.add_edge(
        "generate_answer",
        END
    )

    graph.add_edge(
        "end_with_error",
        END
    )

    return graph.compile()


# ---------------------------------------------------------
# Compile application
# ---------------------------------------------------------

app = build_graph()